### ISSUE TITLE
[ID] [REQUEST]

### ISSUE THREAD

**Issue by andrefsianipar** [gvoze32/unblockhostid#117]

**Comment by gvoze32** [comment]
Oke sabar, nunggu rame dulu

**Comment by zaichikaito** [comment]
[ID] [REQUEST] cosplayjav.pl

**Comment by zaichikaito** [comment]
sama tambahin gan fitur membersihkan cache dns 

"ipconfig /flushdns"

**Comment by zlowly703** [comment]
[EX] [BUG] [PC] mangapark.me
ini keterangannya
The connection to 'mangapark.me' failed. 
Error: TimedOut (0x274c). 
System.Net.Sockets.SocketException A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by gvoze32** [comment]
![image](https://user-images.githubusercontent.com/28755051/37250807-53163c28-2537-11e8-93b0-478faf08f061.png)

**Comment by gvoze32** [comment]
@zaichikaito 

Ok

**Comment by andrefsianipar** [comment]
gan sy udah copy file hosts ke ../drivers/etc tapi beberapa situs masih kena blok internet positif. ISP Telkom

**Comment by gvoze32** [comment]
Emang gk semua, cek supported sites

**Comment by andrefsianipar** [comment]
Ok gan, edit maksudnya beberapa situs di SITES.md juga ada yang diblok. apa tidak cukup dengan menambah ip di host?

**Comment by gvoze32** [comment]
Seharusnya udah bisa pake hosts doang
