### ISSUE TITLE
[ASK] abis update mac 10.14.4, netflix gabisa diakses

### ISSUE THREAD

**Issue by rahardianh** [gvoze32/unblockhostid#605]
hi, sebelumnya I'm a fan of your work on unblockhostid. thank you so much for helping normies like me yang have to deal with indi*** yang gak bisa netflix!

months ago before the latest update, I've followed the guides on my 2017 mac pro and it worked on terminal through this command:
 
sudo curl -sfLS https://raw.githubusercontent.com/gvoze32/unblockhostid/master/hosts >> /etc/hosts

<img width="570" alt="Screen Shot 2019-05-07 at 16 32 01" src="https://user-images.githubusercontent.com/50361390/57289857-64f3d080-70e6-11e9-9cfc-b2433b5d3cde.png">

namun, after update I have to deal with input commandnya di terminal lagi dan sekarang gak bisa diakses. any solutions or update that I've missed perhaps?

<img width="1040" alt="Screen Shot 2019-05-07 at 16 37 14" src="https://user-images.githubusercontent.com/50361390/57289973-a5ebe500-70e6-11e9-9ea8-8f6844545d82.png">

**Comment by gvoze32** [comment]
Updated - Fixed Netflix Bugs
https://github.com/gvoze32/unblockhostid/commit/3fcbf772531759c7fc523b2d5df38d3d152ee7ee

But i don't update the raw file in here because this is an quick update, so i uploaded the raw file mirror to pastebin so linux/mac user can do the update without running the _.exe_ file.

Here's the link: https://pastebin.com/raw/JYKxa7wN

and you can just do

`sudo curl -sfLS https://pastebin.com/raw/JYKxa7wN >> /etc/hosts`

**Comment by rahardianh** [comment]
turns out all I have to do is re write the hosts and reinput the sudo u gave me earlier. cheers!
